name: Mingw-w64 Cross CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: setup mingw
      run: |
        sudo apt update
        sudo apt install gcc-mingw-w64-x86-64 binutils-mingw-w64-x86-64
    - name: make
      run: |
        make

    - uses: actions/upload-artifact@v2-preview
      with:
        path: ./*.exe
