name: Mingw-w64 Cross CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: setup mingw
      run: |
        sudo apt update
        sudo apt install gcc-mingw-w64-x86-64 binutils-mingw-w64-x86-64
    - name: make
      run: |
        make

    - uses: actions/upload-artifact@v1
      with:
        name: Launcher.exe
        path: Launcher.exe
    - uses: actions/upload-artifact@v1
      with:
        name: Alpine.exe
        path: Alpine.exe
    - uses: actions/upload-artifact@v1
      with:
        name: Arch.exe
        path: Arch.exe
    - uses: actions/upload-artifact@v1
      with:
        name: Artix.exe
        path: Artix.exe
    - uses: actions/upload-artifact@v1
      with:
        name: CentOS.exe
        path: CentOS.exe
    - uses: actions/upload-artifact@v1
      with:
        name: Clear.exe
        path: Clear.exe
    - uses: actions/upload-artifact@v1
      with:
        name: Debian.exe
        path: Debian.exe
    - uses: actions/upload-artifact@v1
      with:
        name: Fedora.exe
        path: Fedora.exe
    - uses: actions/upload-artifact@v1
      with:
        name: Gentoo.exe
        path: Gentoo.exe
    - uses: actions/upload-artifact@v1
      with:
        name: Ubuntu.exe
        path: Ubuntu.exe
    - uses: actions/upload-artifact@v1
      with:
        name: Void.exe
        path: Void.exe
    - uses: actions/upload-artifact@v1
      with:
        name: openSUSE.exe
        path: openSUSE.exe
