name: Release

on:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: setup MinGW
      run: |
        sudo apt update
        sudo apt install gcc-mingw-w64-x86-64 binutils-mingw-w64-x86-64
    - name: make
      run: |
        make

    - uses: actions/create-release@v1
      id: create_release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false

    - name: Upload Launcher.exe
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: Launcher.exe
        asset_name: Launcher.exe
        asset_content_type: application/octet-stream

    - name: Upload Alpine.exe
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: Alpine.exe
        asset_name: Alpine.exe
        asset_content_type: application/octet-stream

    - name: Upload Arch.exe
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: Arch.exe
        asset_name: Arch.exe
        asset_content_type: application/octet-stream

    - name: Upload Artix.exe
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: Artix.exe
        asset_name: Artix.exe
        asset_content_type: application/octet-stream

    - name: Upload CentOS.exe
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: CentOS.exe
        asset_name: CentOS.exe
        asset_content_type: application/octet-stream

    - name: Upload Clear.exe
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: Clear.exe
        asset_name: Clear.exe
        asset_content_type: application/octet-stream

    - name: Upload Debian.exe
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: Debian.exe
        asset_name: Debian.exe
        asset_content_type: application/octet-stream

    - name: Upload Fedora.exe
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: Fedora.exe
        asset_name: Fedora.exe
        asset_content_type: application/octet-stream

    - name: Upload Gentoo.exe
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: Gentoo.exe
        asset_name: Gentoo.exe
        asset_content_type: application/octet-stream

    - name: Upload Ubuntu.exe
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: Ubuntu.exe
        asset_name: Ubuntu.exe
        asset_content_type: application/octet-stream

    - name: Upload Void.exe
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: Void.exe
        asset_name: Void.exe
        asset_content_type: application/octet-stream
